apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  template:
    metadata:
       name: myapp-pod
       labels:
         app: backend-app
         tier: back-end
    spec:
      containers:
       - name: backend-container
         image: python  
  selector:
    matchLabels:
       tier: back-end
       app: backend-app