apiVersion: apps/v1
kind: Deployment
metadata: 
   name: practice-deployment
   labels:
     tier: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
       name: demoapp-pod
       labels:
         app: demoapp
         tier: frontend
    spec:
      containers:
        - name: simple-webpage
          image: nginx