apiVersion: v1
kind: Pod
metadata:
  name: python-app
  labels:
    type: front-end
spec:
  containers:
    - name: python-container
      image: python-app
      env:
        - name: POSTGRES_PASSWORD
          value: mysecretpaswsword