apiVersion: apps/v1
kind: Deployment
metadata:
  name: resultapp-deployment
  labels:
    app: demo-voting-app
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
     name: result-app
     app: demo-voting-app
     type: frontend
  template:
    metadata:
      name: result-app
      labels:
        name: result-app
        app: demo-voting-app
        type: frontend
    spec: 
     containers:
       - name: result-app
         image: kodekloud/examplevotingapp_result:v1
         ports:
          - containerPort: 80
    