apiVersion: v1 
kind: Pod
metadata:
   name: postgres-pod
   labels:
     app: demo-voting-app
     type: database
spec: 
  containers:
    - name: postgresdb 
      image: postgres
      ports:
       - containerPort: 5432
      env: 
       - name: POSTGRES_USER
         value: "Teja"
       - name: POSTGRES_PASSWORD
         value: "Teja"
      