apiVersion: v1 
kind: Pod
metadata: 
  name: worker-pod
  labels:
    app: demo-voting-app
    type: backend 
spec:
  containers:
   - name: worker-role
     image: kodekloud/examplevotingapp_worker:v1
