apiVersion: v1 
kind: Service
metadata:
  name: postgres
  labels:
   name: postgres-service
   app: demo-voting-app
spec:
  type: ClusterIP
  ports:
   - targetPort: 5432
     port: 5432
  selector:
   app: demo-voting-app
   type: database