apiVersion: v1 
kind: Service
metadata:
  name: resultapp
  labels:
   name: resultapp-service
   app: demo-voting-app
spec:
  type: NodePort
  ports:
   - targetPort: 80
     port: 80
     nodePort: 30008
  selector:
     name: result-app
     app: demo-voting-app
     type: frontend