apiVersion: v1 
kind: Service
metadata:
  name: voteapp
  labels:
   name: voteapp-service
   app: demo-voting-app
spec:
  type: NodePort
  ports:
   - targetPort: 80
     port: 80
     nodePort: 30005
  selector:
    app: demo-voting-app
    type: frontend